server:
  port: 8082

spring:
  application:
    name: iam-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:data_extraction}?currentSchema=iam_schema
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:changeme}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: iam_schema
  flyway:
    enabled: true
    schemas: iam_schema
    default-schema: iam_schema
    create-schemas: true

logging:
  level:
    root: INFO
    com.extraction: DEBUG
